application: la-cantora
version: 1
runtime: python
api_version: 1

handlers:
# static files
- url: /static
  static_dir: www/static
# - url: /()
#   static_files: www/\1
#   upload: www/()
# script handlers
- url: .*
  script: website.py
